# Generated by Django 4.2 on 2023-04-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_name', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('tovar_id', models.AutoField(primary_key=True, serialize=False)),
                ('tovar_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('tovar_price', models.IntegerField(verbose_name='Цена')),
                ('tovar_disc', models.TextField(blank=True, verbose_name='Описание')),
                ('tovar_photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='фото')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['tovar_name', 'tovar_price', 'tovar_id'],
            },
        ),
    ]
