# Generated by Django 4.2 on 2023-04-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovar',
            old_name='category_id',
            new_name='category',
        ),
    ]
